### ISSUE TITLE
Олег, проснись, ти сереш

### ISSUE THREAD

**Issue by bringmetheaugust** [Nitroglicerine/JavaScript-exercises#3]
https://github.com/Nitroglicerine/JavaScript-exercises/blob/070c6278b95ff7865072c2619c82fa08f53d8847/src/transport/Car.js#L41C33-L41C33
поправь

**Comment by Nitroglicerine** [comment]
ok

**Comment by bringmetheaugust** [comment]
Issue закриваєшь тільки тоді, коли ти її поправив і воно вже в `main`
